export let MidiDrumCodes = new Map([
  [39, 'Hand Clap (D#)'],
  [37, 'Side Stick (C#)'],
  [35, 'Accoustic Bass Drum (B)'],
  [36, 'Bass Drum 1 (C)'],
  [38, 'Accoustic Snare (D)'],
  [40, 'Electric Snare (E)'],
  [41, 'Low Floor Tom (F)'],
  [43, 'High Floor Tom (G)'],
  [45, 'Low Tom (A)'],
  [47, 'Low-Mid Tom (B)'],
  [48, 'Hi-Mid Tom (C)'],
  [50, 'High Tom (D)'],
  [42, 'Closed Hi-Hat (F#)'],
  [44, 'Pedal Hi-Hat (G#)'],
  [46, 'Open Hi-Hat (A#)'],
  [49, 'Crash Cymbal 1 (C#)'],
  [51, 'Ride Cymbal 1 (D#)'],
  [54, 'Tambourine (F#)'],
  [56, 'Cowbell (G#)'],
  [58, 'Vibraslap (A#)'],
  [59, 'Ride Cymbal 2 (B)'],
  [57, 'Crash Cymbal 2 (A)'],
  [55, 'Splash Cymbal (G)'],
  [53, 'Ride Bell (F)'],
  [52, 'Chinese Cymbal (E)'],
  [70, 'Maracas (A#)'],
  [68, 'Low Agogo (G#)'],
  [66, 'Low Timbale (F#)'],
  [63, 'Open Hi Conga (D#)'],
  [61, 'Low Bongo (CH)'],
  [73, 'Short Guiro (C#)'],
  [75, 'Claves (D#)'],
  [78, 'Mute Cuica (F#)'],
  [80, 'Mute Triangle (G#)'],
  [60, 'Hi Bongo (C)'],
  [62, 'Mute Hi Conga (D)'],
  [64, 'Low Conga (E)'],
  [65, 'High Timbale (F)'],
  [67, 'High Agogo (G)'],
  [69, 'Cabasa (A)'],
  [71, 'Short Whistle (B)'],
  [72, 'Long Whistle (C)'],
  [81, 'Open Triangle (A)'],
  [79, 'Open Cuica (G)'],
  [77, 'Low Wood Block (F)'],
  [76, 'Hi Wood Block (E)'],
  [74, 'Lon Guiro (D)'],
]);
